In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from nltk.tokenize import word_tokenize, wordpunct_tokenize
from nltk.corpus import stopwords 
import nltk 
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\HeatoN
[nltk_data]     Ma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\HeatoN
[nltk_data]     Ma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
#file = open("Desktop/medicaltranscriptions.csv",encoding='gb18030', errors='ignore')
#raw_data_1 = file.read()
#file.close()

In [3]:
data = pd.read_csv("medicaltranscriptions.csv") 

In [4]:
data.head()

Unnamed: 0                                        description  \
0           0   A 23-year-old white female presents with comp...   
1           1           Consult for laparoscopic gastric bypass.   
2           2           Consult for laparoscopic gastric bypass.   
3           3                             2-D M-Mode. Doppler.     
4           4                                 2-D Echocardiogram   

             medical_specialty                                sample_name  \
0         Allergy / Immunology                         Allergic Rhinitis    
1                   Bariatrics   Laparoscopic Gastric Bypass Consult - 2    
2                   Bariatrics   Laparoscopic Gastric Bypass Consult - 1    
3   Cardiovascular / Pulmonary                    2-D Echocardiogram - 1    
4   Cardiovascular / Pulmonary                    2-D Echocardiogram - 2    

                                       transcription  \
0  SUBJECTIVE:,  This 23-year-old white female pr...   
1  PAST MEDICAL HISTORY:, He has difficulty climb...   
2  HISTORY OF PRESENT ILLNESS: , I have seen ABC ...   
3  2-D M-MODE: , ,1.  Left atrial enlargement wit...   
4  1.  The left ventricular cavity size and wall ...   

                                            keywords  
0  allergy / immunology, allergic rhinitis, aller...  
1  bariatrics, laparoscopic gastric bypass, weigh...  
2  bariatrics, laparoscopic gastric bypass, heart...  
3  cardiovascular / pulmonary, 2-d m-mode, dopple...  
4  cardiovascular / pulmonary, 2-d, doppler, echo...

In [5]:
description = data.description

In [6]:
description.head()

0     A 23-year-old white female presents with comp...
1             Consult for laparoscopic gastric bypass.
2             Consult for laparoscopic gastric bypass.
3                               2-D M-Mode. Doppler.  
4                                   2-D Echocardiogram
Name: description, dtype: object

In [7]:
des_str = description.to_string() 
stop_words = set(stopwords.words('english')) 
word_tokens = wordpunct_tokenize(des_str)
word_tokens = [w.lower() for w in word_tokens] 
word_tokens = [w.lower() for w in word_tokens if not w in stop_words] 
word_tokens = [w.lower() for w in word_tokens if w.isalpha()] 

In [8]:
#vocab = set(word_tokens)
#char_to_int = dict((c,i) for i,c in enumerate(vocab))
#int_to_char = dict((i,c) for i,c in enumerate(vocab))

In [9]:
word_occurences = pd.Series(word_tokens).value_counts()
word_top10 = word_occurences[:10]
word_top10 # Top 10 Word Occurences in "description"

patient      747
left         596
right        529
old          380
year         332
pain         224
female       189
bilateral    175
history      170
ct           126
dtype: int64

In [10]:
word_tokens

['year',
 'old',
 'white',
 'female',
 'presents',
 'comp',
 'consult',
 'laparoscopic',
 'gastric',
 'bypass',
 'consult',
 'laparoscopic',
 'gastric',
 'bypass',
 'mode',
 'doppler',
 'echocardiogram',
 'morbid',
 'obesity',
 'laparoscopic',
 'antecolic',
 'anteg',
 'liposuction',
 'supraumbilical',
 'abdomen',
 'echocardiogram',
 'suction',
 'assisted',
 'lipectomy',
 'lipodystrophy',
 'echocardiogram',
 'doppler',
 'morbid',
 'obesity',
 'laparoscopic',
 'roux',
 'en',
 'gastr',
 'normal',
 'left',
 'ventricle',
 'moderate',
 'biatrial',
 'enla',
 'cerebral',
 'angiogram',
 'moyamoya',
 'disease',
 'patient',
 'presented',
 'bariatric',
 'surgery',
 'se',
 'surgical',
 'removal',
 'completely',
 'bony',
 'impacted',
 'preoperative',
 'visit',
 'weight',
 'management',
 'neck',
 'exploration',
 'tracheostomy',
 'urgent',
 'flexib',
 'patient',
 'status',
 'post',
 'lap',
 'band',
 'placement',
 'fertile',
 'male',
 'completed',
 'family',
 'elective',
 'patient',
 'year',
 'old',
 '

In [11]:
nltk.download('averaged_perceptron_tagger')
pos = nltk.pos_tag(word_tokens)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\HeatoN Ma\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [12]:
pos

[('year', 'NN'),
 ('old', 'JJ'),
 ('white', 'JJ'),
 ('female', 'NN'),
 ('presents', 'NNS'),
 ('comp', 'VBP'),
 ('consult', 'NN'),
 ('laparoscopic', 'NN'),
 ('gastric', 'JJ'),
 ('bypass', 'NN'),
 ('consult', 'NN'),
 ('laparoscopic', 'NN'),
 ('gastric', 'JJ'),
 ('bypass', 'NN'),
 ('mode', 'NN'),
 ('doppler', 'NN'),
 ('echocardiogram', 'NN'),
 ('morbid', 'NN'),
 ('obesity', 'NN'),
 ('laparoscopic', 'VBZ'),
 ('antecolic', 'JJ'),
 ('anteg', 'JJ'),
 ('liposuction', 'NN'),
 ('supraumbilical', 'JJ'),
 ('abdomen', 'NNS'),
 ('echocardiogram', 'VBP'),
 ('suction', 'NN'),
 ('assisted', 'VBN'),
 ('lipectomy', 'JJ'),
 ('lipodystrophy', 'NN'),
 ('echocardiogram', 'NN'),
 ('doppler', 'NN'),
 ('morbid', 'NN'),
 ('obesity', 'NN'),
 ('laparoscopic', 'NN'),
 ('roux', 'NN'),
 ('en', 'IN'),
 ('gastr', 'NN'),
 ('normal', 'JJ'),
 ('left', 'VBD'),
 ('ventricle', 'NN'),
 ('moderate', 'JJ'),
 ('biatrial', 'JJ'),
 ('enla', 'NN'),
 ('cerebral', 'JJ'),
 ('angiogram', 'NN'),
 ('moyamoya', 'NN'),
 ('disease', 'NN'),


In [13]:
pos_noun = []
for i in pos:
    noun = ['NN', 'NNP', 'NNS', 'NNPS']
    if i[1] in noun:
        pos_noun.append(i)

In [14]:
pos_n = []
for i in pos_noun:
    pos_n.append(i[0])
pos_n_occurences = pd.Series(pos_n).value_counts()
pos_n_occurences[:10]           #  Top 10 Word Occurences for nouns only

patient         482
year            332
pain            205
history         170
female          120
evaluation      108
ct              103
mri              93
consultation     83
laparoscopic     76
dtype: int64

Question 5

In [18]:
from gensim.models import KeyedVectors
import gensim.downloader as api
print(api.load("word2vec-google-news-300", return_path=True))

[=================================================-] 99.9% 1661.4/1662.8MB downloaded
C:\Users\HeatoN Ma/gensim-data\word2vec-google-news-300\word2vec-google-news-300.gz


In [20]:
model = KeyedVectors.load_word2vec_format('Desktop/PubMed-and-PMC-w2v.bin', binary=True)

In [42]:
# Access vectors for specific words with a keyed lookup:
vector = model['allergy']
# see the shape of the vector (200,)
vector.shape

(200,)

In [45]:
try:
    for i in pos_n:
        vectors = model[i]
except KeyError:
     pass            # We skipped the KeyError because not all words find the corresponding vector representations

In [46]:
vectors

array([ 0.31116557,  0.19298121, -0.1587466 , -0.41777083, -0.03171469,
       -0.0602666 , -0.04416724, -0.06001487,  0.02735449,  0.3957696 ,
       -0.64750946, -0.19317746,  0.04250947, -0.19637665,  0.07191874,
        0.21497928,  0.22741558,  0.00635937, -0.13025442, -0.11483578,
        0.08104119,  0.02273043, -0.02214913,  0.08656038,  0.06836606,
        0.36975893, -0.06944272,  0.37279984,  0.13977562,  0.12966228,
        0.27328157, -0.0888297 , -0.03787299,  0.04203958, -0.07120068,
        0.26168373,  0.0576332 , -0.15607585, -0.03579465,  0.15061998,
        0.26317966, -0.1507776 , -0.38752058,  0.06976836, -0.11025204,
       -0.08963262, -0.08034819, -0.17155063, -0.29438728, -0.29024136,
        0.26369086, -0.07669822, -0.11188981,  0.08014958, -0.17847845,
        0.00785908, -0.05611166, -0.11482495,  0.11813919, -0.03911375,
        0.1129273 ,  0.04637966,  0.21226503, -0.02226496,  0.10039023,
       -0.10672288, -0.01497133,  0.00558604,  0.09677673,  0.38

Question 6

In [29]:
from sklearn.metrics.pairwise import cosine_similarity
v1=np.array(model['allergy'])
v2=np.array(model['allergic'])
cosine_similarity([v1], [v2])

array([[0.73083645]], dtype=float32)

In [30]:
v3=np.array(model['heart'])
v4=np.array(model['lung'])
cosine_similarity([v3], [v4])

array([[0.39735395]], dtype=float32)

In [31]:
v5=np.array(model['water'])
v6=np.array(model['-heart'])
cosine_similarity([v5], [v6])

array([[-0.02294649]], dtype=float32)

In [32]:
model.most_similar("allergy")

[('allergies', 0.8844105005264282),
 ('sensitizations', 0.763312816619873),
 ('allergens', 0.7619640827178955),
 ('IgE-mediated', 0.7575483322143555),
 ('hymenoptera-venom', 0.7375401258468628),
 ('non-IgE-mediated', 0.7373875379562378),
 ('allergic', 0.7308364510536194),
 ('atopy', 0.719882071018219),
 ('sensitisation', 0.7056722640991211),
 ('allergen', 0.702096700668335)]